version: '3.8'

services:

  type-controller-app:
    build:
      context: ./
      target: prod
    links:
      - postgres-db
    volumes:
      - .:/src
    command: npm run start
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=prod
      - PORT=3000
    restart: on-failure
  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: audvice
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: